version: "3"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
#    command: ["python3", "main.py"]
    restart: always

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
